### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Luci-d**
deleted 25 404 links,  changed few links to live and add one service.
You still have 25 404's, I'm just tired to change all of them

### CODE REVIEW

**Comment by m4ll0k** [comment]
thank's very much!!!!

**Comment by sv0** [comment]
I went through the diff and have found that some deleted links are still available.
May be it's worth to check them manually before removal. 

For example:
Link to the **Cisco Router Default Password Scanner** page was [deleted](https://github.com/m4ll0k/Awesome-Hacking-Tools/pull/15/commits/37a7c2aff778be21b0113db98f588354fe7c0d1a#diff-04c6e90faac2675aa89e2176d2eec7d8L151).
But that page is still available at https://www.question-defense.com/2013/01/11/ocs-version-0-2-release-ocs-cisco-router-default-password-scanner

**Comment by Luci-d** [comment]
> I went through the diff and have found that some deleted links are still available.
> May be it's worth to check them manually before removal.
> 
> For example:
> Link to the **Cisco Router Default Password Scanner** page was [deleted](https://github.com/m4ll0k/Awesome-Hacking-Tools/pull/15/commits/37a7c2aff778be21b0113db98f588354fe7c0d1a#diff-04c6e90faac2675aa89e2176d2eec7d8L151).
> But that page is still available at https://www.question-defense.com/2013/01/11/ocs-version-0-2-release-ocs-cisco-router-default-password-scanner

I checked at list 10 manually and then validated them through Check My Links and Automatic link Checker. But yeah, my bad, I'll check all manually

**Comment by Luci-d** [comment]
> I went through the diff and have found that some deleted links are still available.
> May be it's worth to check them manually before removal.
> 
> For example:
> Link to the **Cisco Router Default Password Scanner** page was [deleted](https://github.com/m4ll0k/Awesome-Hacking-Tools/pull/15/commits/37a7c2aff778be21b0113db98f588354fe7c0d1a#diff-04c6e90faac2675aa89e2176d2eec7d8L151).
> But that page is still available at https://www.question-defense.com/2013/01/11/ocs-version-0-2-release-ocs-cisco-router-default-password-scanner

I checked at list 50% of all links that I'm gonna remove, every time. But still, sorry for that. I'll check them manually

**Pull request merged**
